services:
  - type: web
    name: hotel-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://hotel_user:<db_password>@cluster0.3s4isxq.mongodb.net/?appName=Cluster0
